"""
Django settings for ids_backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)

# Prioritize .env in local directory for standalone app
if (BASE_DIR / '.env').exists():
    env.read_env(BASE_DIR / '.env')
elif (BASE_DIR.parent / '.env').exists():
    # Only fallback to root if local doesn't exist
    env.read_env(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7#$#a2m%83o5o6-(toq^*d_jqw*mw*-qt4fcmym(5-%&fei&!)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)
API_BASE_URL = env('API_BASE_URL', default='http://localhost:8000')

raw_hosts = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
ALLOWED_HOSTS = []
CORS_ALLOWED_ORIGINS = []
CSRF_TRUSTED_ORIGINS = []

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    for host in raw_hosts:
        host_str = host.strip().strip("'").strip('"')
        if not host_str:
            continue
            
        # Extract domain for ALLOWED_HOSTS
        clean_domain = host_str.replace('https://', '').replace('http://', '').split('/')[0].split(':')[0]
        if clean_domain and clean_domain not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(clean_domain)
            
        # Determine specific origins for CORS/CSRF
        if host_str.startswith(('http://', 'https://')):
            origin = host_str.rstrip('/')
            CORS_ALLOWED_ORIGINS.append(origin)
            CSRF_TRUSTED_ORIGINS.append(origin)
        else:
            # Default to both protocols if not specified
            CORS_ALLOWED_ORIGINS.extend([f"http://{clean_domain}", f"https://{clean_domain}"])
            CSRF_TRUSTED_ORIGINS.extend([f"http://{clean_domain}", f"https://{clean_domain}"])




# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Use the robustly parsed origins from above
    pass # CORS_ALLOWED_ORIGINS is already populated

CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = "ids_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ids_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Model Configuration
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MODEL_DIR = BASE_DIR / "static" / "model"
MODEL_PATH = str(MODEL_DIR / "Hybrid_CNN_ConvNeXtTiny_Final.pth")

# WhiteNoise configuration for static files
# In development, we allow WhiteNoise to use finders if it's enabled
if not DEBUG:
    WHITENOISE_USE_FINDERS = False
    WHITENOISE_AUTOREFRESH = False
else:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}

if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append(
        'rest_framework.renderers.BrowsableAPIRenderer',
    )

DEVICE = env('DEVICE', default='cpu')
